import os
import subprocess
from pathlib import Path
from .config import *

def catgt_command(dir_name: str, probes: str, event_bits: list,
                  data_path: Path, output_path: Path=None,
                  nidq: bool=True, car: str=None, inverted: bool=False):
    """
    Generate command for CatGT v3.4-4.3
    Parameters:
        dir_name (str): exact name of top-level sglx run, e.g. "20250507_CW001_00_g0"
        probts (str): "0" for single probe recording, "0:1" for 2-probe recording 
        event_bits (list): list of digital bits you want to extract from NIDAQ
        data_path (Path): directory containing raw SGLX recording session folder
        output_path (Path): destination directory for processed data
        nidq (bool): ?
        car (str): "global", "local", or None
    Returns:
        command (str): CatGT command line command
    """
    
    # Inputs
    probes = str(probes)
    event_bits = [str(event_bit) for event_bit in event_bits]

    # Create NIDAQ params
    if nidq:
        if inverted:
            extractor_str = "ixd"
        else:
            extractor_str = "xd"
        event_extractors = []
        for bit in event_bits:
            # extractors format: stream_type,stream_index,word,bit,min_width_ms
            event_extractors.append(f"-{extractor_str}=0,0,-1,{bit},0")
        nidq_command = f"-ni {' '.join(event_extractors)}"
    else:
        nidq_command = ""

    # Imec data referencing
    if car=="global":
        car_command = "-gblcar"
    elif car=="local":
        car_command = "-loccar=4,32"
    elif car==None:
        car_command = ""
    else:
        raise ValueError("Invlid CAR type.")
    
    # Construct command
    command = f"CatGT -dir={data_path} -run={dir_name[0:-3]} -prb_fld -g={dir_name[-1]} -t=0 -ap -prb={probes} {car_command} {nidq_command} -dest={output_path} -out_prb_fld"
    
    return command
 
def run_catgt(command: str, catgt_program_path: Path=CATGT_PATH):
    """
    Run catgt command as subprocess (in CLI).
    
    Parameters:
        command (str): command generated by catgt_command()
        catgt_program_path (Path): location of CatGT executable
    """
    
    # Format command
    full_command = f"cd {str(catgt_program_path)} && {command}"

    # Run as subprocess
    status = subprocess.run([part.strip() for part in full_command.split(" ")], capture_output=True, text=True, shell=True)

    return status.returncode

def catgt_pipeline_node(session_sglx_path: Path, session_cgt_path=None, probes="0:1", event_bits=[1,2]):
    """Pipeline node for running catgt."""

    # Find session catgt folder
    if session_cgt_path is None:
        session_cgt_path = session_sglx_path.parent.parent / "ephys_catgt"
    if not session_cgt_path.exists():
        os.mkdir(session_cgt_path)

    # Generate command and run
    command = catgt_command(session_sglx_path.name, probes, event_bits,
                            data_path=session_sglx_path.parent, output_path=session_cgt_path,
                            nidq=True, car="global", inverted=False)
    status = run_catgt(command)
    return status